# Generated by Django 4.0.1 on 2022-08-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_deal_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='OrderItem',
        ),
    ]
