# Generated by Django 4.0.6 on 2022-10-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
