# Generated by Django 4.0.6 on 2022-10-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='addon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.addon'),
        ),
    ]
