# Generated by Django 4.0.6 on 2022-11-08 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_telephone_alter_order_customer_alter_review_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
