# Generated by Django 4.0.6 on 2023-01-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
