# Generated by Django 4.0.6 on 2022-10-18 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0008_telephone_alter_order_customer_alter_review_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('second_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('has_premium', models.BooleanField(default=False)),
                ('telephone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.telephone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
