# Generated by Django 4.0.6 on 2022-10-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_telephone_alter_order_customer_alter_review_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0002_alter_profile_email_alter_profile_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.telephone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
