# Generated by Django 4.0.6 on 2022-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_profile_telephone_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
